### ISSUE TITLE
imp variable not used fully for energy calculation

### ISSUE THREAD

**Issue by igardner82** [aegjoyce/bthome-electricity-meter#1]
Many thanks for the great code, got it running mostly successfully on my puck.js with HA.

My meter has a 1000 / kWh impulse rate, so I have updated the 'imp' variable accordingly, but I have noticed the reported energy rate is still out.  I think it stems from Line 42: 

`energy = counter * 0.3125;`

I think it should be the following to convert correctly based on different imp values:

`energy = counter * 1000 / imp;`

Thanks again
Ian

**Comment by aegjoyce** [comment]
Great spot - I've updated the code with this suggestion. Many thanks.
