### ISSUE TITLE
Seeed XIAO BLE

### ISSUE THREAD

**Issue by Mosher23** [aegjoyce/bthome-electricity-meter#2]
Hello,

i like your solution with puck.js for power metering. However it is relatively expensive for what it is.
Is it possible for you to adjust your code to utilize much cheaper solution from Seeed Stuidio? It's just 1/4 of the price of puck.js and has more updated nrf chip on it.

https://www.seeedstudio.com/Seeed-XIAO-BLE-nRF52840-p-5201.html?queryID=c23ea68a99e21db349895d4605228754&objectID=5201&indexName=bazaar_retailer_products

Looking forward to hear from you back

thanks

**Comment by aegjoyce** [comment]
Beyond the scope of this project, sorry.
