### ISSUE TITLE
Puck for media control on Home assistant

### ISSUE THREAD

**Issue by bouton** [aegjoyce/bthome-electricity-meter#3]
Wow this is great!

I found this while I was looking for hints on how to convert  from my current espruino hub/mqtt script to a BThome for Home Assistant.  I must confess my eyes cross at the hex code. 

I currently use my puck for simple control of my Sonos on my desk. Just a simple on/off and up/down volume control via a long/short set of button pushes.

I successfully send BLE advertising for battery (0x180F), on/off (UUID digital 0x2A56), volume (UUID alert_level 0x2A06) cause those were the only standards I could see that espruino hub worked with. These get converted by the espruiono hub on a pi pico to send as mqtt then into an automation.  Works grand.

But I'd like to get the hub out of the picture if possible and try bthome off a esphome device I am also using near my desk for presence detection.

Can I be cheeky and ask for some help on converting this? Keep in mind I am a hacker so the below may not be perfect.

This is what I now have on my puck.

```
var SWBtn = require("SWButton");
var buttonState = 0;
var advData = {};
var idleTimeout;

var mySWBtn = new SWBtn(function(k){
  if (k === "S"  ) { // single button press
    buttonState = !buttonState;
    advData[0x2A56] = buttonState; //UUID digital
    advData[0x2A06] = 0; ///UUID alert_level 0-no level
  }
  else if (k === "L" ) { // long button press
    advData[0x2A06] = 1; //UUID alert_level mid level
  }
  else if (k === "SS") { // double short press
    advData[0x2A06] = 2; ///UUID alert_level high level
  }
  updateAdvertising(advData);
});

//start with advertising temperature and battery level
setInterval(function () {
  advData[0x180F] = [E.getBattery()];
  NRF.setAdvertising(advData);
}, 1*60*1000); // 1 min

function updateAdvertising(advData) {
  NRF.setAdvertising(advData);
  if (idleTimeout) clearTimeout(idleTimeout);
  idleTimeout = setTimeout(function() {
    idleTimeout = undefined;
    advData[0x2A06] = 0; ///UUID alert_level 0-no level
    NRF.setAdvertising(advData);
  },2500);
}
```

I think I just need help "converting" what gets advertised to a bthome format?

Anyway - happy to see the puck being used on a home assistant project.  It was a great device to learn on.

Thanks

**Comment by aegjoyce** [comment]
So your Puck sends a message to HA (via espruino hub) and then HA controls the Sonos via the integration?
You'll be able to advertise battery level fine but you can't advertise events (button presses) as they are not yet supported in HA so I don't think you currently have a way to make this work.
You might find another way around this - look at my hex values and see how they match up with the advertising format (https://bthome.io/v1/) and then play around. Good luck!

Closing issue as it is beyond the scope of this repo.

**Comment by bouton** [comment]
thanks - that was my next option. Should give me a head start just seeing how you have done it.
